version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: extended-umbrella-lnswitchboard_app_1
      APP_PORT: 22121
      PROXY_AUTH_WHITELIST: "/.well-known/*"
      PROXY_AUTH_ADD: "true"
  app:
    image: ghcr.io/ryleastark/lnswitchboard:0.0.98@sha256:825052c8df9faaef6166f9e7e1f1bc875cb31bd493788bc77d875946639d4b7d
    restart: unless-stopped
    environment:
      SERVICE_PORT: 22121
      LND_HOST: "$APP_LIGHTNING_NODE_IP"
      LND_GRPC_PORT: "$APP_LIGHTNING_NODE_GRPC_PORT"
      LND_TLS_PATH: "/lnd/tls.cert"
      DATA_STORE_PATH: "secrets/lnswitchboard.db"
    volumes:
      - ${APP_DATA_DIR}/data/secrets:/app/secrets:rw
      - ${APP_DATA_DIR}/data/logs:/app/logs:rw
      - ${UMBREL_ROOT}/app-data/lightning/data/lnd:/lnd:ro