version: "3.9"

services:
  lnswitchboard:
    image: ghcr.io/ryleastark/lnswitchboard:latest@sha256:2657c13c53d3bfbb0721772b116d170318120bf42537b9b5bcaaf990a25161ad
    restart: unless-stopped
    environment:
      SERVICE_PORT: 22121
      LND_HOST: "$APP_LIGHTNING_NODE_IP"
      LND_GRPC_PORT: "$APP_LIGHTNING_NODE_GRPC_PORT"
      LND_TLS_PATH: "/lnd/tls.cert"
    volumes:
      - ${APP_DATA_DIR}/data/secrets:/app/secrets:rw
      - ${APP_DATA_DIR}/data/logs:/app/logs:rw
      - ${UMBREL_ROOT}/app-data/lightning/data/lnd:/lnd:ro
    ports:
      - "22121:22121"