version: "3.9"

services:
  lnswitchboard:
    image: ghcr.io/ryleastark/lnswitchboard:latest@sha256:86e07b57efb5e3f15fb032db47826087b266a4e160645c2b9791c2e0611bc822
    restart: unless-stopped
    environment:
      SERVICE_PORT: 22121
      LND_HOST: "$APP_LIGHTNING_NODE_IP"
      LND_GRPC_PORT: "$APP_LIGHTNING_NODE_GRPC_PORT"
      LND_TLS_PATH: "/lnd/tls.cert"
    volumes:
      - ${APP_DATA_DIR}/data/secrets:/app/secrets:rw
      - ${APP_DATA_DIR}/data/logs:/app/logs:rw
      - ${UMBREL_ROOT}/app-data/lightning/data/lnd:/lnd:ro
    ports:
      - "22121:22121"